services:
  db:
    networks:
      - caddy_network

  db-populator:
    networks:
      - caddy_network

  spring:
    labels:
      caddy: https://api.archnite.omarashraf.dev
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - caddy_network

  frontend:
    labels:
      caddy_0: https://archnite.omarashraf.dev
      caddy_0.reverse_proxy: "{{upstreams 80}}"
      caddy_1: https://www.archnite.omarashraf.dev
      caddy_1.redir: https://archnite.omarashraf.dev
    networks:
      - caddy_network

networks:
  caddy_network:
    external: true
