services:
  db:
    networks:
      - caddy_network

  db-populator:
    networks:
      - caddy_network

  spring:
    labels:
      caddy: https://api.archnite.omarashraf.dev
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - caddy_network

  frontend:
    labels:
      caddy: https://archnite.omarashraf.dev
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - caddy_network

networks:
  caddy_network:
    external: true
