services:
  db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5
      timeout: 3s
    networks:
      - app-network

  db-populator:
    build: ./archnite-db-populator
    container_name: db-populator
    restart: always
    depends_on:
       db:
          condition: service_healthy
    env_file:
      - .env
    environment:
      DOCKER_COMPOSE_ENV: "true"
    networks:
      - app-network

  spring:
    build: ./archnite-spring
    container_name: spring
    restart: always
    depends_on:
       db:
          condition: service_healthy
    env_file:
      - .env
    environment:
      DOCKER_COMPOSE_ENV: "true"
    ports:
      - ${SPRING_PORT}:8080
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
