spring.application.name=archnite
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/archnitedb
spring.datasource.username=postgres
spring.datasource.password=secretpass
spring.jpa.hibernate.ddl-auto=validate
